osx_image: xcode10.2
language: swift
xcode_project: SwiftGS1Barcode.xcodeproj # path to your xcodeproj folder
xcode_scheme: SwiftGS1Barcode
xcode_destination: platform=iOS Simulator,name=iPhone X,OS=11.4
